version: "2"
services:
  give-pgadmin:
    image: dpage/pgadmin4:7.7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_USER
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_PASSWORD
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "4000:80"
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  pgadmin:
